{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b2177ff5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Data Augmentation (DA) Technique"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "73fb05a1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# pip install Pillow"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "33d619c4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAiUAAAClCAMAAAC0nH0oAAAC+lBMVEX////59+1KSkrMzMyZmZn8/f2ZTABMAJkzZgAAmZn5+fmYmJiFhYVmADPv7u5UVFTJycnU1NRaWlrx8fGhoaFfX1/b29vS0tLAwMDIyMhzc3NiYmL7+/uAgH9OTk719fXDw8PY2Nibm5twcHD+/v7o6OjX19f01Id9fX353JC6urqampqDg4FMTEy9vb3r6+vGxsWMjIzx0IeJiYhnZ2fPz8+1tLRXV1f424yzs7L22Ij39/e3t7d3d3f59+yqqqr53pWfn56dnZ3vzId5eXmFo2fi4uGsrKzz8/P18Ojl5eXe3t6/v7+Dg4OwsLCUlJNra2ueVA1/n1/p6env7+dkZGQ9bg3ry4lRUVG4uLiurq6np6cJnZ2kpKOQkI9cXFz39Ov2so/p2cjl0b1vk0xnJqhSfSfq6eH36cSXsX3Lo3ywjtL2uJXy1pPk2fD59eb48t98y8vU38qFUroToaHy6d+7n9kxra2lpaVXEJ/pwoqKPGO+jFzhzdf379W1ldX535rzqYmek4JhYWGhWhX18Prz4LFtL6v41Y7RuoeJh4GVT3JvEECtbzLH6ek+srLgyrG3yaW2fkhFcxe85eVgwMDC0bPfw4jQrYhGtbX34KXav6O4iKD02Y3Ck2Z+KVOoZyek29tfHKTt053yw4msnYOvhIKTjYFqBzjVxOji5trh39fW1tbbw85wxsblz7VwNK7mypLdtYnhvIeFNFxhiTr6+v3z+/vt7e3n5+eY1tbd29OK0NCmgMzQz8medcggpqbVt5iiZIPHnHOxdz3s+PhUurqrco6juozAq4a4ioSfhoDv6PbM6+vWu8iTZcLw48G/larvnoi4loOaV3l3HUrk9fXt4Oa04eHr3tHW1M7O2sK/vbh+R7V4P7LEjI7ml4nbzOvIseDCp9za19DPr7/GxL7Dm66mpqaZmJSPq3PEmGylYR7H1bl5m1jE6OjNuOPvv6KtwpnTkpbipYmpl4Pa8PDU7u7JpLaxfZfb1Mnx9e6oqKWAoGDvoT+MAAAbzUlEQVR4nO2dCVgUR9rHy6LnNCNEUERR5NggooKACKIo4sURlTiCKCKRCGiCGqMBPEhC1HixajxAjfGOicb7yMb7jibuqhtNolF3NzEmJub8stns7vc9z1dV3TPTPTNM90wPc0j9Hx+6u7pmumvmZ9X7Vnf/BwAqKioqKioqKioqKioqKiqqxlX3tinuPgVbGjs8xt2n0CQ1JLwlEoS+6O/ILAWEoe4+I1t6FXZ09yk0SQ2CPGUjSp4w7urdboxlfauF4lK8/noEXi7buMfBEyVqBdvIeTmVo8ry8/PrCGEaWgQCASXhsJVldauF4pqhVGbg5ZvKNx08TyJKiRulhfBxsiKgZGjLAMuqVgvFZaBkNqXEa8Wn5N1ufVqF99WijcCR+CsZ0TyhXaduCkNVq4XjN67LOFv78PV1wWijWe13EafPbTwLQPDpcw9rzyI6ZmxUIs09O2kuXmy8CWafI0FyRu1Z00mkJA9oN7x9Mj5yhN+TCQldYtn3529QStwoPiWtSIQyAH0p0fAxAFr7ku22IVxVq4WTlDk5mAPluWYAFCtzZuP1iIxaUpZTjIqIas+xy2UKpXI8ft0yZY7xHDJHsrFRuAKEdGFX2+P3F2xQStwoPiXw1dEdh0HYDYDmGIi2cHjHwLEdYCJX1WrhJAzI6XVvKpWvA4JEztn64ohzypzv1qHuI2cGGH9aqVy3J6Noz1zlwz3jQbAlJUNawVHNO7YJ6wpbgCch7J7dpjsiA+0QbFBK3CgBJfj/bDz+TjAQiq6wNdpu3b8FV9VqIaJkNk5h1imVpOPIuUk2yCJjIw5FhHGJFUoYOAq/J2jdAwQRRgFAMXWscINS4k7xKcnGy0ScyZBuoydsHsyvarUQUdKMrLyOIECU1LPrbNCxTjk3QpSS4J5wsOHd2sMn2ZXHYCfhBqXE1dLyZjEtcpwg6MsBMRjClsN6GONU64WT8EiDdVpZiykhQOBAFUuJt8UoGQSh8XzGGVDoCFsKNyglLpZPWpZpw4ISPyMloO8oNAq18zNUtVo4STmbXVmmfIgpIetKo3KaiVLyOIQRhnfrCgONhQrBBqXEpQqtZBhbfQmPEuCf36kD7GCYuLdaaOxL1rF9CVnPUdaPZ5UhHpegvsTfcDYtDdPwsbCncINS4kJhRhiGV2CDEpLs+reF3bmqVgtRXMJeJJyNOhUDJeeU35mOIKQkQqkkE/WnjZRoR8HOhroDDO9bCAcINyglLlNmMkKkOVPJK2qYks6QTLUm49CRyGohooQQUYy/fQMlp7kOYwaeOjObe32onIT+NttoynEK4bg/4WVrP9AGQh+8GtgVpTeCDUqJi8QxwjDJvEJblMD40JigVtAwL2+1EM+XzN4zflION19CCoNrlTln9xTXz1WeA6BIqVyGMflOeW5GMF7k1Bev26g0URLjC8eNDgwM6ApjFH1g17AePfp3gH0UQLBBKXGJ/PMZg3x4xXxKSKxBKGHw4BLNzny2M0QNVgsRJezca20GmXtlS2fUKo2FAM/RjyczKpikjLmGwNZ4DoE92TftpMBjGTsNi+djBBuUEldImxnqk1xJehPBfSR9XuW+8AHthuBFTMt4lA779karPu17dmgXZgwtrRai6HXGm3NzNtbj6CTj4WzD0U6fm5tTW0+mVsbXKmtnoIjku7k5eDZlxuy5yo31p5UbTecQEzayg2+ffJxfB/du6+sbnqgl5fyNYS0znflxUDWsICYMceLMj9uY49ip2Q6+jqrRNYhheiBKtE58S/spIZMjN5XK0048CyrnKSWAiQXZTJoz39NuSs7mnC0eX5+j3OhMVqmcp25MXxQfClIc2bKbktls7PrwpjPPgsppCmX643mJ7Gxnvmlxjp0jh7a+FgW7k4qceRJUTpN/f4bkvP6B7j4TKo+VYjTTWbwWVdNWEBPg0U9lUXmARjDMIHefA5WHK+UblARTUdkUSYKpqGyJS4KpqBqWIQmmompQETQJphKVD02CqcQkLQluLJOb1SXfc38cFfW3cYG03zBB1spdZHLzf+qB3B9HRf1tXKDsBpJgF5ncPIUBeUoOJfRexsZX6waTYNeY3FBK7JFP48nWYf3TbCbBjW9yQymxRz7NGku2KBFLguWa3EwrWR4ysaRkOQD6iYdWHLrIRcCrnykpGbjjc1xuouSHQ2Sv/tC3puNTfxuh3ENJD5EkWK7JzUT1oRK1Wv0MmLZCjVVSit/0B7KuXoHKTZQo1Opp+CWr1bnGw1N/GzO5hZIRYSJJsFyTm4mYjIkXd+hXqFdMXD5QrT6EIPsWYbN8+TOEHhMlwZaUUH8bc7mDEutJsDbTNP8g1+QGUVKCH+MZqC75L1pMU6uXgx1q9US871tRSqi/jbncQYllEpwZmF3JpJluX5drcoMo+Ry/Ta56NdkeiMCYqC4hRw0Wo4T621jIDZQIk2D/0Nhk9glQ3u3Rck1uECV4gbqP3BVYaAl+UHPh6UARSqi/jYVcT0kIPwn2SSOA4IfJGX9THbkmNxMxCAB8rjbqEDikvsjuvChCCfW3sZDLKYlIFCTB/tkYkuaIE/6TFnJNbjhKdqKBZxqrFNSXTGR3fivel1B/G6FcTolFEuwfG0Y6E/61M7kmNxwlKbkoagXGskPsSq6Akgi1mlzy+8VICfW3sZCrKbFMgrW9GdyVCB7tk2tyw1GC+o8SPV6uLiE5Do5owffC6BWUkD4mpMSU41B/G3O5mBLLJLjFGCZ6qLnjgFyTGwMlO3LVKy5+vnogSYIHqnOXp6QszzWjBBVf/Hx5idpECfW3MZdESor0zVLRorQ0tVlRUTOy7hAlHZnRwiR4UBoTkJnFMH0FpXJNbgyUgO/ZuVf1UyhRTnnGEMoKKNFzVXhzr9TfxkwSKMFY6O8VNdM3yziRkVGkL2qWWuogJVlMf3/h4REf/sCfYczuIpFpcvN9LpfPAP3EktzcQ+ysSfAvh3Jzn5m2OvcXAJbnLuf+gNKnVqhLLv6iLjEdnvrbCCWBkowdGfqjyTuL7hXd6l2q1+/IyMjYWeQQJSFmV4KDezNMZzwdllZpWdnF+sHQ/VBZSoySIjTEnCgtunc/WX+0dEfADv2J23r90ewicUwsKTFLgoF/XyaanYHId+evrpHJkWlq9S9uPAcPlwglGfqM1NQdsaU7bz04cev2iQe3Su/fLj0x+H6qI5SYJcGZASgkYVcD3egt823ut59Pu5irLqG3ajcoEUpSS3fqU3fG3o7NHt3/f4dFF94am3hiZ0DYrVLx+NWCkj8Jk+DAaBySuF9PcfcTHHX3iXiwREece0f1O0vHBgwd0717fPyiB/877FZAdOFRvSgkFpRo+/KT4ODOXEjidmkvHlqRWzLxv+4+D0+WaPSacSJ2Z6zfg8Jhj3VBii8sXJQW/+CEOCQWlAiSYBSShL3r2pZSOS7xHKd08NCxaYMXdWmPhP5gVNIy7KdEkATjkOQPLm4pleMSpyTVb+yD+GEIjvbtO7GUFErpSswoESTBKCQZHWJ+JlSeKwnzJan3oxdhSEhvgjBZJKkrMaOElwTjkKQNNaTwJkmaob+V1h1TsgipS5dFD+5JeY2QkkBTEoxDkiesnAmV50radZyi+zXbt9fUXNq2raYmYKeklwgo4SXBNCTxQkm82lddt7AuL7JXUtL6uGopl/qElChMSTANSbxR0iiZsjYuslevXklR/fr1e3mq3ZTEGpJgGpJ4p6RRUrYeQ8JS0q9MWmdiomSQIQkOoSGJd0oSJVPLIxElSUmYkpdffrnaPkpCArj7Av5AQxIvlRRKUudzXQlHydopdlGSyJBnncATYTQk8VJJoQR3Jaa+BP2TNOYYKHmcTYIVbRwKSRrLC0m+FJ3aR4jXEsizGmNHA6TMqqGoJDKS7UtIYNJPUmfCUfKn/iQJDhktMSRxkReSfI2AsIVYHY9ujJQGcJJAyRTclQgoeblMMiVcEiw9JHGRF5J8/UHCh+zRjZHSAE4SKKnGXYlpzMGgrJUw5LCUsEmwPSGJa7yQ5EvSh+zJjXEuJfMj49LrFhLV1e1bT4ITCXMmhBKSBOOQJNaukKTxvZDkS/KH7KmNcSolqeVxdZe2bd++aBGepN+2sG5fVJSUIQdTkoKTYByStLavAXK9kMB7xypOLT12Hq2tWvoeLjhfsRuAP57a9MnuilNrNrEVFUeWnqrY/Qlga61cc+rCecPrJZghOUSJA43JSuBcWbIT8Nv4dBmZ0J18nIkJWZndR7Zt7R8+jPdiTjEBbVuFx5MZ75RE1JZC7htwpAFSKJlavrBm0faaf27bhv/VbN++bWG5lCEHU9IZJcEoJKlsyBk1tIH7XeV6IZ2v0GBN/xdQaDR/xCUrNQUAPK8pKCA7CDmfcJVWAlxrFV7/kXu9FDMkhyhxoDH50JdkRopWMBkoCtkTwNYZbeFjuOaYHnAUqdjfYJyB5DeKrReG2pLArgZEONoAKZSUIUhqLqHBpq4uL69u4SWEzKXyl8WzHB82CUYhSXKD+V9omo9VTuR6IT2vmX7kxyPTNRfMKUGAHNmEgLiA/lct1RTs3vT8dM30T3AtxMmxTdzLJZkhOUSJA40ZMgrm42UQ7OAPAiCM7z10OIRBuB6EfQYnhvSAHUjFMNjF+Ll2hePGxHZ+DCbgtvj275jfB8LRjjZAAiWpay9tr1m4b19eJL7Y12v9loVo9NnXTzww8SFJMA5JbGTllYxVTuR6IS3VHEN/z+/+swUlq/DJbNJoVqI/BX/GlU5pVhFKNpkOL8kMyTFKHGhMIQzHi/YwHozoSthRPAlHEkoKcWusUDIcDifXRPwGoe7JF89ERDSHHVo42AAJlEwpr7u0cNn48XsQJkm9tly9enXZpW15/cQDEx+UBHcUC0lCGcYaJ3K9kC5olnIhhjklbPEaRMYazW6yvkkzHdcqML1amhmSQ5Q40phQCLPI7EYg6AuHk6IYXIQoIc89WlLSGkLDp47aMpRdGYca5VgDJFAytTwub8/OQaWl6+Iie+27qdfrS+fnrY+aL05JENN3bMMhCadKxhoncr2QfizQFFzYhIMPM0rWsPuPaCoADkmw0PI8qnXEdHRpZkiO5zh2Ngb1DCg8DUCjBzoB2JMIwo6IEtLHWKGkN+5qWGUaz3IY6osaakCmmHevyHedWl0et+/oztjbg47GRcYVl8ae0Otn9EtKEg9fuzHR0cw3QSKHz8cWNxacyPVCAp+dQl9+wTELSlZxuzWngMao6e8ZarGSZobkOCX2NqY3il8V43CfEG6aowtElLCP4FtSMgb2sWwLLmyoAT6MbdmmZMrU6vmRcVuOHu3f/X7p1ritO+4P61/aQr8F5cJTUm1zou9vcMISE1upkv8El1wvJAAOf7YK9RLHGuhLNqG+pEDz/J9ZnQdCSqSZITmFEkmNSfGF+R3hqCF4oBjQmtX7wAYlibjfMW8Lfu+GGiCrL0ktm7+lPC5u2b17wxbdHr9163M3kxfFDyKU9CsrK7OZ5xSlMWGdxW3I84lflh19iSQvJDJFotiNegwEw2d4A0cfOC4he1DcsgpFuLuNxxNSIs0MyRmUSGoMHizCB8BCQIYdUypgoAT1C+TDizdSgkreNxzcl2uLoh0c42ADROKS6vKZB9Lj4vb95+jt5GU/P/30cz8XJ94eoZ9RHhUVVb5A5NJwWnObTvScJMYl9nkh/atg6WG8wP1HBTvKoHiWUELIWKlB6Bzhpkd+q9htRok0MyQnUCLN2Im7HBTKrpC4OuWxPsFGSkhcC0AWNFIS8SrsRALgoNaIsJYj8Oo3EI5wsAEilMzP278/Ly4ub9l//lOMIHn6ued+vlmKotckpMj0BTYvDWdEM0yy6FlIyHEc8EL6TaOp+OyTPy7FZBxDZKxcuYqEp3i+5MJnPz5fgEeewxWagt2frTw2HdUyo0SSGZJTKJFi7ARI0jucrAxDO2MDeydA3yFGSkACfLVb4GBfEyXoCDC827s+8bAdaNESthwdGBQP8fs51gARSrbMJJSk71u37udXXkGQPPfcnuLi+QuSohAlW+PW2pw0aYMAiA4SMROQMF/iiBfSJnaKtQB99Yo1bIh6IYJQwu6owNPy3Nwr3jCjRJIZkuQL73Ibg9QNwt7se8WzO3u+axpxQI+uXERrmnsdypWMQR3iOHa1UOFoA8QpOYApSZ954BVECcGkvBxBEhUlTonP46ibYAJsT5c0MPcq1wsJ/LbqVMH0C//Cq4pjFQUFFUfweI6i199WTS+oOMZGJ+8dWYo38Ke35tR7guNLMEMKHh4u8Qqm3MYgONoON8xfx7Yfh3bir7fS1/Ck9eMDfEeF+8WT0IVTaHyrri2fJBmN/9iEUS07+QHHGyAy4iBKUFyCONlqpGTBgiispF5bI23fjOQDYpnobtHMUBvANnQdp5FkzHEeRaFcua94LcdkO3rdd2AmpiQ9fetf/8oNOQtYTJJ6pS+wPf/qg72PAjKHig87LtOjSgnJe5IhbDSjN5uUFJXt2ZJONPPvCBMcvz5t6EsWpIvcZIKCae1gZrC2dYDIsOM6PaKUhLcaHBrIoLi20Y5ge1Ytdep83JNgSv5OKHnaQEm/tWUiD/nhlGtIAJMYoQ2yPey4To8mJQr2dgTYdkijHUJshp5PCcZkayRHSZmYsxpJzN+Pxre9tkj2jGFn5fQj4pW8TzHNE3BE2ojPTIpTgiHJm/krhwmiJIlQIvroFjun9gTD4DkCDxp2qOyXGCVX9+UhzZy5/1cSmWyNw3eZIInfYMLNvAYx0Xi22HOGHSr7JU5J/ceXLtXv37//119/fWVrOkp58vLqDiwsl0oJTnTIgOkpww6V/RKlJG9/zUcf1dTU/PPDDz/8+OOP/7ltG/r7cZ34LY2Gqzgk0SFrdNjxVolRUlaeXv/WR0hvYX34N7L24YH180XvLzFe6yOJDlmjw46XSoyS6vK49AMfv/XWR3/D+p8PMSr1M9eLB688Z4r3w4wmN3TY8UqJUTJlC45EDuxHhCChUWfSgbzyqCgJTwrz7hvIYhMdIjrseKFE72i8Wp4eFxkZmT4T6cCBmXlx66OikiR0JQJfNS7RIaLDjvdJ/B76+agzwQ8JR/aKjGOfFU6SEJUIKYnozCU6RHYNO465OUx+7biEWs9OmOzAe3NywJnCayXh2b4teYQTRAnxukGS8MyWmZNnMEp0eI8P2Bp2nOLm8KJqgoRae1XPOvDenOy4PcPrJeFp8qlbZublxRFQiPXA+vmS/PeE9zOiRKcz77+ecNgRVHWKmwOfkisTfmqg8bIoseNWL6+XlF9km3p1Sx7mBI04kevXllVLMswy96HnJTpEvGHHn/+D085xc+BRolWprjTQeEqJREly35sytbq6rKzsall19dQpU+z3eyVCiU6WoMA47GQKfyYWS66bA78veWHzFw00nlIiUVJ/KTaVk8TqVigBPkzY+4ICw7CTyTCBZnXlWlNwlChO7p3HxqhX7mq/uLP5tSuXye7DL93dvPf4PI6SL+5MmHBl8jsTvjQd37nGDl4vV/6esCDRIWKHHdTLpNl41MIRawqWksMvqFT/AK+pXgIKlWqCCmszzmouv8auV2FKcCWypXrBeHgnGzt4vVxJiVmiQ4SHnc4Mw+QLi+VaUxBK5t1VqVBCzFGi2vzsF8dVGAUFKr/y5UsYFUTJSVT25ZcYFSMlzjZ28Hq59LfJh4wVJDpE2iD2EVBhzCLXzQFTcnmvCvFhomQeWn9WVaVAO1U/ofXDdzElkwlJLCyGozvb2MHr5dpfsI8JM/8Be5ThJLLPCTf4CKgjbg6IksloiCGRBkcJWf+HSnUZ3OF4mIwpOa6aQKKZwyZKnG7s4PVyLSWWiQ4ITOMeKo/ll8p1c3gRxxmqd8g6RwnZmKdSTQabVVzSsxlR8oLqJLtxxUiJ3cYOj7xcTIl5ohOTbDIe4D8nINfN4UUSkDZACQ5pie4gSu4asuHjRkrsNnZ45OVqSoSJjtbHJz85uZIFZTCvllw3B0RJFfpHLtNYUFJFwhLAzpcY+5KTRkrsNnZ45OVySoKHWiY6iIrMzEwfnm2SXDcHRMnlyVWqzXh6xIKSu2y8ijdwXHKXfUmVkRKnGzt4vVxOCQixkuhYSK6bw4uqzShUrVLtnWeFkhdVVWRy7SSX4/yEN34yRa9ON3bwermeEquJjrnkujmws2pfqFR3FJaUHH5NNeGdw5dPsvMlV1RVX2rnvVjFy4Sdbezg9XIDJVYSHQvJdXPgZuhfwjMmFpSAyew8bBWhZN4dFSfT3KuTjR28Xu6gBPRgwkSsG+W6OUyuYmPS41XvgJNVKKW5MwFPqoGIva9hl6R5xyeoNl+5TPYAxUt7q6ru/OOLqpdMh3eusYPXyy2UoERnbOM91ErldIn74zksG0e1nuhQUQmEEx13nwOVxysmjZFi4UjVtDVIPNGhopKQ6FBRtaGJDpWoFDTRoRIXTXSoJIgmOlQSRBMdKgkKpIkOlbg6GhIdR54Zp2oiMiQ6ofmiVamarkLGkESnMq2B/Y75lzSWmpJpiUepRRrTAz8qbLg3xCn+JY2lpnTrkWcJJzr5DGOAwSn+JY2lpnQbo4cJJToMw2QbNp3hX9JYopS4TZmj8VNblfwiuf4ljSVKiVuU6ZNseLaP/6CwTP+SORuusSu/b9iF/v5l8YYNZ+bg7Wsb5nx6ZsOsOf4Hz5D9uzb8bjooz7SE51PSZE1LPEiZ+cZfnubPwsr0L/lat4RkRoobumsg+IyO6A1UMEu3eAle/YvubVLxA91i4zF5piV8n5Ima1riUfKPTcO/PN1c8Di5TP8S/7d1X+PlV7q3W4B/63TXv752UKf7ClOi081641qIFUp4piUCn5Ima1riYdIGVtp6TtgR/5IzuoN4sVh3HXyq0+HhR7FYt4FQcgZPeFihhGdaIvApabKmJZ6nLByd8Lbl+pfM0elQHIIA2QXeYIHBG3MwJeSCgCUlPNMSoU9JkzUt8UTFZPOtKeT6l4CDOhSe/ht3Hzd0uiVEeMiZxSFjSQnPtEToU9JkTUs8U1ppngOS/EtI/BqMY1fEi1G7ECVvkN2WlPBMS4Q+JU3WtMTzJde/BKQs0X2NYlc0vFzXzZrD6lNggxKeaYnQp6TJmpZ4vuT6l5D4dTEedfCwY7pAZ6Bkl05HpmeuGynhmZYIfUqarGmJ50uufwmJX0kEC7LYmRKQcn2W1kgJiWtJJQMlfNMSgU9JkzUt8XzJ9S8BJOllI9UzOt31r3Z9vUG3ZIiRErBBd+P3XW8sMVHCNy0R+JQ0WdMSz5dc/xKk33XszBrQXmdj1yW7TCMO+MvbXERrmnvlmZbwfUqarGmJF0imfwmSdtYGw/1LXy2+8faND/DX+2+MCtGuWUvePvjVdd0Z0yt4piU8n5Ima1pCxSnihqFvoaKyIpL3XNPpPnX3iVB5rg7eeGPOrg9QXOvuE6HyXKGhhmgWfZ6dqmF9+sGGJUsOXqNPs1NRUVFRUVFRUTVl/T9jbEZt+5a/OQAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<PIL.PngImagePlugin.PngImageFile image mode=P size=549x165>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#Example of agumentation\n",
    "from IPython.display import display\n",
    "from PIL import Image\n",
    "\n",
    "\n",
    "path=\"example.png\"\n",
    "display(Image.open(path))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2a5f8b4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Textattack"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "52843b15",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting textattack\n",
      "  Using cached textattack-0.3.4-py3-none-any.whl (373 kB)\n",
      "Requirement already satisfied: nltk in /home/user/anaconda3/envs/NLP/lib/python3.8/site-packages (from textattack) (3.7)\n",
      "Collecting datasets\n",
      "  Downloading datasets-2.0.0-py3-none-any.whl (325 kB)\n",
      "\u001b[K     |████████████████████████████████| 325 kB 599 kB/s eta 0:00:01\n",
      "\u001b[?25hCollecting scipy>=1.4.1\n",
      "  Using cached scipy-1.8.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.6 MB)\n",
      "Collecting word2number\n",
      "  Using cached word2number-1.1.zip (9.7 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/word2number_5f48af50b95442a6b1c8469fa466b353/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/word2number_5f48af50b95442a6b1c8469fa466b353/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kzid9y8d\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/word2number_5f48af50b95442a6b1c8469fa466b353/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/word2number_5f48af50b95442a6b1c8469fa466b353/setup.py\", line 12, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/4a/29/a31940c848521f0725f0df6b25dca8917f13a2025b0e8fcbe5d0457e45e6/word2number-1.1.zip#sha256=70e27a5d387f67b04c71fbb7621c05930b19bfd26efd6851e6e0f9969dcde7d0 (from https://pypi.org/simple/word2number/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached word2number-1.0.zip (9.4 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/word2number_bacd6e73b921444eb34785fb81017737/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/word2number_bacd6e73b921444eb34785fb81017737/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z6w3enik\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/word2number_bacd6e73b921444eb34785fb81017737/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/word2number_bacd6e73b921444eb34785fb81017737/setup.py\", line 12, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f4/d4/4e18534181f5727a53349043c62c8accb85b7fe613a19e0e788ae9f6ee19/word2number-1.0.zip#sha256=72770e04aa5d74fe5c87b42596d459aa4571561b9f0b6e17358ace3075aeb321 (from https://pypi.org/simple/word2number/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached word2number-0.2.zip (8.6 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/word2number_17565801e6134e28945dee985a496337/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/word2number_17565801e6134e28945dee985a496337/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vrpbe6x5\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/word2number_17565801e6134e28945dee985a496337/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/word2number_17565801e6134e28945dee985a496337/setup.py\", line 12, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/a1/2a/e981d3e4ae07a7e387d89d4f493091d62ce86948a8d36ef8e04cdaddaede/word2number-0.2.zip#sha256=227ea7f5193be5cae2904955b3c76d643cc1328be2d692cb6793e7e206720b89 (from https://pypi.org/simple/word2number/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached word2number-0.1.zip (8.1 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/word2number_d8cef7adbda14f83a2d6f69153f26636/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/word2number_d8cef7adbda14f83a2d6f69153f26636/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dfjabig1\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/word2number_d8cef7adbda14f83a2d6f69153f26636/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/word2number_d8cef7adbda14f83a2d6f69153f26636/setup.py\", line 12, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/da/86/370cccd7995df7a5593b05fcb4fea874ded1d7d174a2b919184e535706c2/word2number-0.1.zip#sha256=1b5960d25d7fb97927a1d8bfa9bd0e68e8390451dcfcf678b5a4081dd38638f3 (from https://pypi.org/simple/word2number/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "Collecting textattack\n",
      "  Using cached textattack-0.3.3-py3-none-any.whl (361 kB)\n",
      "  Using cached textattack-0.3.2-py3-none-any.whl (360 kB)\n",
      "  Using cached textattack-0.3.0-py3-none-any.whl (359 kB)\n",
      "  Using cached textattack-0.2.17-py3-none-any.whl (358 kB)\n",
      "  Using cached textattack-0.2.16-py3-none-any.whl (347 kB)\n",
      "  Using cached textattack-0.2.15-py3-none-any.whl (349 kB)\n",
      "  Using cached textattack-0.2.14-py3-none-any.whl (334 kB)\n",
      "  Using cached textattack-0.2.13-py3-none-any.whl (334 kB)\n",
      "Collecting tokenizers>=0.9.3\n",
      "  Using cached tokenizers-0.11.6-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.5 MB)\n",
      "Collecting textattack\n",
      "  Using cached textattack-0.2.12-py3-none-any.whl (333 kB)\n",
      "  Using cached textattack-0.2.11-py3-none-any.whl (318 kB)\n",
      "Collecting wandb\n",
      "  Downloading wandb-0.12.14-py2.py3-none-any.whl (1.8 MB)\n",
      "\u001b[K     |████████████████████████████████| 1.8 MB 1.1 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting flair==0.6.0.post1\n",
      "  Downloading flair-0.6.0.post1-py3-none-any.whl (241 kB)\n",
      "\u001b[K     |████████████████████████████████| 241 kB 910 kB/s eta 0:00:01\n",
      "\u001b[?25hCollecting visdom\n",
      "  Using cached visdom-0.1.8.9.tar.gz (676 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_228b8fa3dc3f4709882ef52702ffb1c7/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_228b8fa3dc3f4709882ef52702ffb1c7/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-h0tg55jv\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_228b8fa3dc3f4709882ef52702ffb1c7/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_228b8fa3dc3f4709882ef52702ffb1c7/setup.py\", line 52, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/c9/75/e078f5a2e1df7e0d3044749089fc2823e62d029cc027ed8ae5d71fafcbdc/visdom-0.1.8.9.tar.gz#sha256=c73ad23723c24a48156899f78dd76bd4538eba3edf9120b6c65a9528fa677126 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.8.8.tar.gz (1.4 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_2a6566a0bb32424795fb642fa8708838/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_2a6566a0bb32424795fb642fa8708838/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-y5xdin84\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_2a6566a0bb32424795fb642fa8708838/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_2a6566a0bb32424795fb642fa8708838/setup.py\", line 51, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/97/c4/5f5356fd57ae3c269e0e31601ea6487e0622fedc6756a591e4a5fd66cc7a/visdom-0.1.8.8.tar.gz#sha256=77edd6811471282740846672a996348e963b5fa4220780f126c71481ad21d5a5 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.8.7.tar.gz (1.4 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_7b47415c206f4a94ae73a6f00b0acc4a/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_7b47415c206f4a94ae73a6f00b0acc4a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-640gkyz4\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_7b47415c206f4a94ae73a6f00b0acc4a/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_7b47415c206f4a94ae73a6f00b0acc4a/setup.py\", line 50, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/85/09/be60dfe97d9ed8c8b17c40fa34cbe50b4652e346b697223846ab0030b9ae/visdom-0.1.8.7.tar.gz#sha256=9261e51b21120aa29158ce329e7e34b4726474630ebb924cc376bfd8a1aa6893 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.8.6.tar.gz (1.4 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_2d8678e5904b4f5cbb603bea73d8850f/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_2d8678e5904b4f5cbb603bea73d8850f/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vr0ooaka\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_2d8678e5904b4f5cbb603bea73d8850f/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_2d8678e5904b4f5cbb603bea73d8850f/setup.py\", line 50, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/1b/52/f7a90cd90029c3fb9237bc6cbf9b5510d2db6e5859ca4dec7a7702f3517d/visdom-0.1.8.6.tar.gz#sha256=0dd7431025da72ab0a893b396df5196c3e40a7e927abd81da928b7e2aee7e1ac (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.8.5.tar.gz (248 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_4ad977aa44104fb796508671685b2da7/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_4ad977aa44104fb796508671685b2da7/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-t2il7u8v\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_4ad977aa44104fb796508671685b2da7/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_4ad977aa44104fb796508671685b2da7/setup.py\", line 44, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/c1/48/d90e1519768107811fd6e7760bea46fff9e9c9ffb490441684003ae634a9/visdom-0.1.8.5.tar.gz#sha256=e9afccf5b64a856d70e2538352a010024324fccaa093df8f3d7890755869136b (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.8.4.tar.gz (246 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_308dc5c0044442779d603760b7953ab3/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_308dc5c0044442779d603760b7953ab3/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yx_dcnei\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_308dc5c0044442779d603760b7953ab3/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_308dc5c0044442779d603760b7953ab3/setup.py\", line 44, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/77/1f/a7a126a63b80ed8c3a9cf099814d09c83def0a54eda0b47ac9dd1f2162de/visdom-0.1.8.4.tar.gz#sha256=7cadee27bd37aec7d5db64caac41f1b4ff140c12e0c6a1b1861f18dd41a190e5 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.8.3.tar.gz (235 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_419c9db217394952a28d4f2103d31199/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_419c9db217394952a28d4f2103d31199/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kzk7412g\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_419c9db217394952a28d4f2103d31199/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_419c9db217394952a28d4f2103d31199/setup.py\", line 23, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/36/f3/ff45f75cadf791e00248af88f98359b4d53da21ba98496406fa08b2bcc6a/visdom-0.1.8.3.tar.gz#sha256=0df89f6ba0c56fc12b40925bfa62dd59549642cd3bf290c394fd27ba5301c133 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.8.2.tar.gz (234 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_ec6c3c3e8b354cd98dd9d50e8ab60764/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_ec6c3c3e8b354cd98dd9d50e8ab60764/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qd1u1m7b\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_ec6c3c3e8b354cd98dd9d50e8ab60764/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_ec6c3c3e8b354cd98dd9d50e8ab60764/setup.py\", line 23, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/87/2a/29a7d3cd4f0f31508b6df50c571336a28e0cf093e29d7c89dedf8a0204c3/visdom-0.1.8.2.tar.gz#sha256=88948dea4ee527d9d6c8a7107ec300e333042d92b5b99978d8a54a0b64056af2 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.8.1.tar.gz (234 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_24e97b76a83f484483bd6864edbcfba6/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_24e97b76a83f484483bd6864edbcfba6/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wbkq3kz8\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_24e97b76a83f484483bd6864edbcfba6/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_24e97b76a83f484483bd6864edbcfba6/setup.py\", line 23, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/5a/25/79ec2e493671587af58dc79d5d2b75361dad3e8a7c17f137b4f66c524152/visdom-0.1.8.1.tar.gz#sha256=2996af7a1c3c4aa01ecae0760353c334c8f8e30b0d3bc954d4ab909ef8203729 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.8.tar.gz (48 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_7289d68cf1c84506874d9bd8d30f3efe/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_7289d68cf1c84506874d9bd8d30f3efe/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mgafsm11\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_7289d68cf1c84506874d9bd8d30f3efe/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_7289d68cf1c84506874d9bd8d30f3efe/setup.py\", line 23, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/3a/12/e3c021894c57fe84762eec469994b098a5df71210e1bbdb5bfedc5b72b46/visdom-0.1.8.tar.gz#sha256=4643c25aed2eaf664d6384d9a267061d99872bf8a508e320b9316a973171ad6f (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.7.tar.gz (43 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_0c2b33e5e50f4b8496afda66aa3c384c/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_0c2b33e5e50f4b8496afda66aa3c384c/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-61if65zl\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_0c2b33e5e50f4b8496afda66aa3c384c/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_0c2b33e5e50f4b8496afda66aa3c384c/setup.py\", line 15, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/0e/f2/27b5d7c34b718afb355587d4e0c1f9108e925db4c0c932e935ba01051efd/visdom-0.1.7.tar.gz#sha256=62732c1e912b8a0819cb3c69a429d0360c291559511ff99932f12bd3f1d1a8bd (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.6.5.tar.gz (39 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_fb1d716ffc7f44d997dc60bf856b4d03/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_fb1d716ffc7f44d997dc60bf856b4d03/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ask6fdbz\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_fb1d716ffc7f44d997dc60bf856b4d03/\n",
      "    Complete output (23 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_fb1d716ffc7f44d997dc60bf856b4d03/setup.py\", line 15, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/c8/e7/9cac06a3c1c2749a18644f1658a4e4fb1187d11978d7e504fba849a2fe0f/visdom-0.1.6.5.tar.gz#sha256=a035a11035fe07cd474e5fc610943c4ff46b7ce8c5830500e7b0377a8bbc2c65 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.6.3.tar.gz (39 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_46c1bec6f0d34f8ab2a09ac66602146a/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_46c1bec6f0d34f8ab2a09ac66602146a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rflk6luw\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_46c1bec6f0d34f8ab2a09ac66602146a/\n",
      "    Complete output (25 lines):\n",
      "    /home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead\n",
      "      warnings.warn(\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_46c1bec6f0d34f8ab2a09ac66602146a/setup.py\", line 15, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ad/0e/8c5c76fa4da12f85f2aae8144e15257250d0dc9d4f9ce51458b23236eb3d/visdom-0.1.6.3.tar.gz#sha256=024a41dc1ec335c3961ab096060e51232a0b765629fea8fbde38de5947565e71 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.6.1.tar.gz (38 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_6ae20f99e3fb435db0c5117c8265ae83/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_6ae20f99e3fb435db0c5117c8265ae83/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-chxyj4qj\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_6ae20f99e3fb435db0c5117c8265ae83/\n",
      "    Complete output (25 lines):\n",
      "    /home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead\n",
      "      warnings.warn(\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_6ae20f99e3fb435db0c5117c8265ae83/setup.py\", line 15, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/18/b2/ffedf7a3aeb602d2f5b057ec185e3151b1a3806fbbd439cccc4fdd50eac9/visdom-0.1.6.1.tar.gz#sha256=cf23729d7e8d10fcae879fdcbd814354f0efd015606de5442a87aa83d3dcab2f (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.6.tar.gz (38 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_abd802e6ca874833a01af67c0d0be748/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_abd802e6ca874833a01af67c0d0be748/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-84g32xaw\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_abd802e6ca874833a01af67c0d0be748/\n",
      "    Complete output (25 lines):\n",
      "    /home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead\n",
      "      warnings.warn(\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_abd802e6ca874833a01af67c0d0be748/setup.py\", line 15, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/e0/a5/59c3ae47c4833727bf89232b61ed0c6fa9152990f95e3f1c106d433e96e5/visdom-0.1.6.tar.gz#sha256=978e2708d44db6ae36835c03f3958617b39d5950f3b9334827d75fcd09c150c5 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.05.tar.gz (32 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_dd1449711a24412fb6b21cbd0f07bb68/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_dd1449711a24412fb6b21cbd0f07bb68/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8tqdi9sc\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_dd1449711a24412fb6b21cbd0f07bb68/\n",
      "    Complete output (21 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_dd1449711a24412fb6b21cbd0f07bb68/setup.py\", line 14, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/5f/bc/cc2b176369402178fb26fd1c365d254f08ab4edab676992d16bb201fbd12/visdom-0.1.05.tar.gz#sha256=08cb193f893da6834ee1b98bda53238f72b33b3fb92c83426d994199a0e80fd8 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.04.tar.gz (29 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_19f134db72884fb1b08efa71e021038a/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_19f134db72884fb1b08efa71e021038a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-y3ehs9_s\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_19f134db72884fb1b08efa71e021038a/\n",
      "    Complete output (21 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_19f134db72884fb1b08efa71e021038a/setup.py\", line 14, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/e0/00/c197e363652b44ea664e68293c5f70d496c856994cda445fdc975acb4636/visdom-0.1.04.tar.gz#sha256=e031abc993645407c692760ba0d6cd4156ebb8b705e981db26960dd02b7d505a (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.03.tar.gz (29 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_fe4e2f91001e47b691a8e9597e706452/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_fe4e2f91001e47b691a8e9597e706452/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4_blkvg0\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_fe4e2f91001e47b691a8e9597e706452/\n",
      "    Complete output (21 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_fe4e2f91001e47b691a8e9597e706452/setup.py\", line 14, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2f/e3/4d3e1fd5b2ea5d547c0877b0d9ce12fc0c65c2187640edde70273c78a4b8/visdom-0.1.03.tar.gz#sha256=cc4024d40bb9c0f6aee6f2b12851618648354473d5f6c0ce243ffd1594d3ed46 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.02.tar.gz (26 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_10134065c9ec455ea46fe47e3ac97915/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_10134065c9ec455ea46fe47e3ac97915/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-he7bcizg\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_10134065c9ec455ea46fe47e3ac97915/\n",
      "    Complete output (21 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_10134065c9ec455ea46fe47e3ac97915/setup.py\", line 14, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/c3/0a/41966452e53678ba40c3404b119656469b3460adfacb770d774de7e617d6/visdom-0.1.02.tar.gz#sha256=aa66985393a9cbdde2571134c9168b58876de771eb98b3bf9e25486e69d25083 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.1.01.tar.gz (25 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_a6b85330de5c40828bb01f2900144664/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_a6b85330de5c40828bb01f2900144664/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xjbvp93c\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_a6b85330de5c40828bb01f2900144664/\n",
      "    Complete output (21 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_a6b85330de5c40828bb01f2900144664/setup.py\", line 14, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/b3/a2/d82885adfa342aa49dfab8f217f669e719f99167143246dac83bbd89ce88/visdom-0.1.01.tar.gz#sha256=13742f2f097a939144d4352684bbdc0a3208fcd4deb6492508a61875eb2a4e52 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.0.9.tar.gz (24 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_24482b3def9f4500964ef0557597e157/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_24482b3def9f4500964ef0557597e157/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4fa5wzz9\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_24482b3def9f4500964ef0557597e157/\n",
      "    Complete output (21 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_24482b3def9f4500964ef0557597e157/setup.py\", line 13, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/c5/2c/01247408c49ec9201a278733fbe2484cc993c7ff839deeb005a7a732cb4d/visdom-0.0.9.tar.gz#sha256=05817f3a7ded2477ae8bb7673399a4f69c906e5b8e391b8e042d8a9a6c63dd31 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.0.4.tar.gz (24 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_1556a90a8a804647a3eaeab6f0f36e25/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_1556a90a8a804647a3eaeab6f0f36e25/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e4ciborn\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_1556a90a8a804647a3eaeab6f0f36e25/\n",
      "    Complete output (21 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_1556a90a8a804647a3eaeab6f0f36e25/setup.py\", line 15, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/20/66/a7643457152e6db04dab4cf0792c6468d7bddf7b0f83ff94b766668cf6b0/visdom-0.0.4.tar.gz#sha256=2227303b03f9c0731bacb927aa62df8e6962ef878bda30a1be89060000b938e2 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.0.3.tar.gz (24 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_ed037e37d80d4fd0b0cc483ffd8f8851/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_ed037e37d80d4fd0b0cc483ffd8f8851/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-18aa59fd\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_ed037e37d80d4fd0b0cc483ffd8f8851/\n",
      "    Complete output (21 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_ed037e37d80d4fd0b0cc483ffd8f8851/setup.py\", line 14, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/da/24/89aecc6192d8120e104d0157be9766ec747a3d1d5d1f78f2a1e38bdbbea6/visdom-0.0.3.tar.gz#sha256=1bab21571f5d41ecc702a21143c9660ac67fe9e31b076b23b8596cbd81049cad (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  Using cached visdom-0.0.2.tar.gz (24 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_cc0a67de1b1a4520acc9a2f21b5553ee/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_cc0a67de1b1a4520acc9a2f21b5553ee/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-y455xyif\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_cc0a67de1b1a4520acc9a2f21b5553ee/\n",
      "    Complete output (21 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_cc0a67de1b1a4520acc9a2f21b5553ee/setup.py\", line 14, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/e8/3b/f4ccb3a12e8954a93cf364d5b0db59f954218d3c560b25eaed55d2e5dede/visdom-0.0.2.tar.gz#sha256=14e0dcfeb3ced396c81ef5777edaf8f6331fccd379264cd191b9a1bcd1ba047d (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached visdom-0.0.1.tar.gz (24 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /home/user/anaconda3/envs/NLP/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-jp4p7fpw/visdom_199f91e707e2489c9590e1d6fd6f382a/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-jp4p7fpw/visdom_199f91e707e2489c9590e1d6fd6f382a/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ex0qlsx4\n",
      "         cwd: /tmp/pip-install-jp4p7fpw/visdom_199f91e707e2489c9590e1d6fd6f382a/\n",
      "    Complete output (21 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-jp4p7fpw/visdom_199f91e707e2489c9590e1d6fd6f382a/setup.py\", line 14, in <module>\n",
      "        setup(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "        _setup_distribution = dist = klass(attrs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 453, in __init__\n",
      "        _Distribution.__init__(\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "        self.finalize_options()\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 830, in finalize_options\n",
      "        for ep in sorted(loaded, key=by_order):\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/setuptools/dist.py\", line 829, in <lambda>\n",
      "        loaded = map(lambda e: e.load(), filtered)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2449, in load\n",
      "        self.require(*args, **kwargs)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2472, in require\n",
      "        items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "      File \"/home/user/anaconda3/envs/NLP/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n",
      "        raise DistributionNotFound(req, requirers)\n",
      "    pkg_resources.DistributionNotFound: The 'tomli>=1.0.0' distribution was not found and is required by the application\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/01/1e/a674de42cc497b3395c4d205bf74f8fba317426d9da792293d1788726a2d/visdom-0.0.1.tar.gz#sha256=30bff9f7ba02017923304a159e4e1383eae85d392c3720f76a66d2e291d9ac05 (from https://pypi.org/simple/visdom/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "Collecting textattack\n",
      "  Using cached textattack-0.2.10-py3-none-any.whl (214 kB)\n",
      "Collecting nlp\n",
      "  Downloading nlp-0.4.0-py3-none-any.whl (1.7 MB)\n",
      "\u001b[K     |████████████████████████████████| 1.7 MB 679 kB/s eta 0:00:01\n",
      "\u001b[?25hCollecting textattack\n",
      "  Using cached textattack-0.2.8-py3-none-any.whl (207 kB)\n",
      "  Using cached textattack-0.2.7-py3-none-any.whl (207 kB)\n",
      "  Using cached textattack-0.2.6-py3-none-any.whl (207 kB)\n",
      "  Using cached textattack-0.2.5-py3-none-any.whl (207 kB)\n",
      "  Using cached textattack-0.2.4-py3-none-any.whl (207 kB)\n",
      "  Using cached textattack-0.2.3-py3-none-any.whl (205 kB)\n",
      "  Using cached textattack-0.2.2-py3-none-any.whl (201 kB)\n",
      "  Using cached textattack-0.2.0-py3-none-any.whl (195 kB)\n",
      "  Using cached textattack-0.1.5-py3-none-any.whl (180 kB)\n",
      "Collecting transformers>=3\n",
      "  Downloading transformers-4.18.0-py3-none-any.whl (4.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 4.0 MB 1.2 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting textattack\n",
      "  Using cached textattack-0.1.4-py3-none-any.whl (177 kB)\n",
      "  Using cached textattack-0.1.3-py3-none-any.whl (177 kB)\n",
      "  Using cached textattack-0.1.2-py3-none-any.whl (162 kB)\n",
      "  Using cached textattack-0.1.1-py3-none-any.whl (161 kB)\n",
      "  Using cached textattack-0.1.0-py3-none-any.whl (161 kB)\n",
      "  Using cached textattack-0.0.3.1-py3-none-any.whl (147 kB)\n",
      "  Using cached textattack-0.0.3.0-py3-none-any.whl (147 kB)\n",
      "  Using cached textattack-0.0.2.6-py3-none-any.whl (140 kB)\n",
      "  Using cached textattack-0.0.2.5-py3-none-any.whl (139 kB)\n",
      "  Using cached textattack-0.0.2.4-py3-none-any.whl (130 kB)\n",
      "  Using cached textattack-0.0.2.3-py3-none-any.whl (148 kB)\n",
      "  Using cached textattack-0.0.2.2-py3-none-any.whl (152 kB)\n",
      "  Using cached textattack-0.0.2.1-py3-none-any.whl (152 kB)\n",
      "  Using cached textattack-0.0.2.0-py3-none-any.whl (152 kB)\n",
      "  Using cached textattack-0.0.1.9-py3-none-any.whl (141 kB)\n",
      "  Using cached textattack-0.0.1.7-py3-none-any.whl (113 kB)\n",
      "Requirement already satisfied: tqdm in /home/user/anaconda3/envs/NLP/lib/python3.8/site-packages (from textattack) (4.64.0)\n",
      "Collecting language-tool-python\n",
      "  Downloading language_tool_python-2.7.0-py3-none-any.whl (34 kB)\n",
      "Collecting tensorflow-hub\n",
      "  Downloading tensorflow_hub-0.12.0-py2.py3-none-any.whl (108 kB)\n",
      "\u001b[K     |████████████████████████████████| 108 kB 655 kB/s eta 0:00:01\n",
      "\u001b[31mERROR: Cannot install textattack==0.0.1.7, textattack==0.0.1.9, textattack==0.0.2.0, textattack==0.0.2.1, textattack==0.0.2.2, textattack==0.0.2.3, textattack==0.0.2.4, textattack==0.0.2.5, textattack==0.0.2.6, textattack==0.0.3.0, textattack==0.0.3.1, textattack==0.1.0, textattack==0.1.1, textattack==0.1.2, textattack==0.1.3, textattack==0.1.4, textattack==0.1.5, textattack==0.2.0, textattack==0.2.10, textattack==0.2.11, textattack==0.2.12, textattack==0.2.13, textattack==0.2.14, textattack==0.2.15, textattack==0.2.16, textattack==0.2.17, textattack==0.2.2, textattack==0.2.3, textattack==0.2.4, textattack==0.2.5, textattack==0.2.6, textattack==0.2.7, textattack==0.2.8, textattack==0.3.0, textattack==0.3.2, textattack==0.3.3 and textattack==0.3.4 because these package versions have conflicting dependencies.\u001b[0m\n",
      "\u001b[?25h\n",
      "The conflict is caused by:\n",
      "    textattack 0.3.4 depends on word2number\n",
      "    textattack 0.3.3 depends on word2number\n",
      "    textattack 0.3.2 depends on word2number\n",
      "    textattack 0.3.0 depends on word2number\n",
      "    textattack 0.2.17 depends on word2number\n",
      "    textattack 0.2.16 depends on word2number\n",
      "    textattack 0.2.15 depends on word2number\n",
      "    textattack 0.2.14 depends on word2number\n",
      "    textattack 0.2.13 depends on word2number\n",
      "    textattack 0.2.12 depends on word2number\n",
      "    textattack 0.2.11 depends on visdom\n",
      "    textattack 0.2.10 depends on visdom\n",
      "    textattack 0.2.8 depends on visdom\n",
      "    textattack 0.2.7 depends on visdom\n",
      "    textattack 0.2.6 depends on visdom\n",
      "    textattack 0.2.5 depends on visdom\n",
      "    textattack 0.2.4 depends on visdom\n",
      "    textattack 0.2.3 depends on visdom\n",
      "    textattack 0.2.2 depends on visdom\n",
      "    textattack 0.2.0 depends on visdom\n",
      "    textattack 0.1.5 depends on visdom\n",
      "    textattack 0.1.4 depends on visdom\n",
      "    textattack 0.1.3 depends on visdom\n",
      "    textattack 0.1.2 depends on visdom\n",
      "    textattack 0.1.1 depends on visdom\n",
      "    textattack 0.1.0 depends on visdom\n",
      "    textattack 0.0.3.1 depends on visdom\n",
      "    textattack 0.0.3.0 depends on visdom\n",
      "    textattack 0.0.2.6 depends on visdom\n",
      "    textattack 0.0.2.5 depends on visdom\n",
      "    textattack 0.0.2.4 depends on visdom\n",
      "    textattack 0.0.2.3 depends on visdom\n",
      "    textattack 0.0.2.2 depends on visdom\n",
      "    textattack 0.0.2.1 depends on visdom\n",
      "    textattack 0.0.2.0 depends on visdom\n",
      "    textattack 0.0.1.9 depends on visdom\n",
      "    textattack 0.0.1.7 depends on visdom\n",
      "\n",
      "To fix this you could try to:\n",
      "1. loosen the range of package versions you've specified\n",
      "2. remove package versions to allow pip attempt to solve the dependency conflict\n",
      "\n",
      "\u001b[31mERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install textattack"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "4efbf7ee",
   "metadata": {},
   "outputs": [],
   "source": [
    "# !python -m pip install textattack>=0.0.2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "c782ff20",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'textattack'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Input \u001b[0;32mIn [7]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mtextattack\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01maugmentation\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m WordNetAugmenter\n\u001b[1;32m      2\u001b[0m text \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mstart each day with positive thoughts and make your day\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m      3\u001b[0m wordnet_aug \u001b[38;5;241m=\u001b[39m WordNetAugmenter()\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'textattack'"
     ]
    }
   ],
   "source": [
    "from textattack.augmentation import WordNetAugmenter\n",
    "text = \"start each day with positive thoughts and make your day\"\n",
    "wordnet_aug = WordNetAugmenter()\n",
    "wordnet_aug.augment(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "27c18af1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a50d3966",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:NLP] *",
   "language": "python",
   "name": "conda-env-NLP-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
